// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFERYKLXSZC--ki2i03uAzv8sxT7zm4BQ',
    appId: '1:34232538402:web:b27e9c9f165f3af1efc17b',
    messagingSenderId: '34232538402',
    projectId: 'cityway-d3cfb',
    authDomain: 'cityway-d3cfb.firebaseapp.com',
    storageBucket: 'cityway-d3cfb.appspot.com',
    measurementId: 'G-5YNJ8ZJNYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-xnyN-mum6c7h92MGLnx6c_LcJ-x8_o',
    appId: '1:34232538402:android:dee8c2cf73271024efc17b',
    messagingSenderId: '34232538402',
    projectId: 'cityway-d3cfb',
    storageBucket: 'cityway-d3cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5KjJPEw__m9zgQeYcilkHyNaE-7oaXg',
    appId: '1:34232538402:ios:5129baddcd241e0fefc17b',
    messagingSenderId: '34232538402',
    projectId: 'cityway-d3cfb',
    storageBucket: 'cityway-d3cfb.appspot.com',
    iosBundleId: 'com.cityway.cityWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5KjJPEw__m9zgQeYcilkHyNaE-7oaXg',
    appId: '1:34232538402:ios:64457060693e0ddeefc17b',
    messagingSenderId: '34232538402',
    projectId: 'cityway-d3cfb',
    storageBucket: 'cityway-d3cfb.appspot.com',
    iosBundleId: 'com.cityway.cityWay.RunnerTests',
  );
}
